import { AdminRole } from '../types';

export const ROLE_PERMISSIONS: Record<AdminRole, string[]> = {
  super_admin: [
    'dashboard:view',
    'orders:view',
    'orders:manage',
    'orders:refund',
    'products:view',
    'products:manage',
    'products:delete',
    'inventory:view',
    'inventory:manage',
    'customers:view',
    'customers:manage',
    'prescriptions:view',
    'prescriptions:review',
    'discounts:view',
    'discounts:manage',
    'shipping:view',
    'shipping:manage',
    'tax:view',
    'tax:manage',
    'analytics:view',
    'audit_logs:view',
    'compliance:view',
    'compliance:manage',
    'staff:view',
    'staff:manage',
    'roles:view',
    'settings:view',
    'settings:manage',
  ],
  compliance_officer: [
    'dashboard:view',
    'orders:view',
    'products:view',
    'compliance:view',
    'compliance:manage',
    'audit_logs:view',
    'roles:view',
    'analytics:view',
    'settings:view',
  ],
  clinical_specialist: [
    'dashboard:view',
    'orders:view',
    'prescriptions:view',
    'prescriptions:review',
    'products:view',
  ],
  support_agent: [
    'dashboard:view',
    'orders:view',
    'orders:manage',
    'customers:view',
    'customers:manage',
    'products:view',
    'inventory:view',
    'discounts:view',
  ],
  fulfillment_specialist: [
    'dashboard:view',
    'orders:view',
    'orders:manage',
    'inventory:view',
    'inventory:manage',
    'shipping:view',
    'shipping:manage',
  ],
  customer: [],
};
